theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

deployment:
  targets:
    - name: "production"
      URL: "s3://66c5de7f746ff9544eed6d07ed92798df688197e53123525d983ec8d11cdb3dd?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
