params:
  cdnkey: https://osuny-1b4da.kxcdn.com
  cookie_banner:
    enable: false
baseURL: https://osuny-example-journal.netlify.app/
defaultContentLanguage: fr
languageCode: fr
languages:
  fr:
    title: Osuny journal example
theme: osuny-hugo-theme
paginate: 18
permalinks:
  posts:          /actualites/:year/:month/:day/:slug/
  categories:     /actualites/:sections/:slug/
  persons:        /equipe/:slug/
  researchers:    /equipe/:slug/publications/
  articles:       /articles/:slug/
taxonomies:
  researcher:     researchers
  volume:         volumes
